SWHC001-05 submission1
sound-data/DEER-Prototypes-EnergyPlus pull request #19
Opened 2024-01-26 17:23 UTC by simularis

We are sharing our work on SWHC001-05 transition to EnergyPlus.

This branch of changes includes a few changes beyond the measure definition. Here is an outline:

- Normalizing units: we wanted to extract heating capacity from models. For that we created a second query file. However, the rakefile seems to trigger simulation runs after we change the query file. So we also included a script to extract that data outside of the rakefile.
- To insert normalizing units into sim_annual style tables prior to further calculations, we also included a script to insert the units into sim_annual. Note that the script includes the residential adjustment steps (number of dwelling) units to match the expectation in post-processing script.
- In residential data transformation scripts, we made adjustment that corrects an issue where more than one "Common_PreTechID" in the batch of measures causes the renaming step to fail silently and generate duplicate rows with mismatched data.

Behzad was the main contributor to this work. @behzadsalimian

2024-02-08 20:25 UTC, simularis commented
If it helps, I can split this into multiple requests and include the pull request template ...

2024-02-08 20:29 UTC, amine-lazrak commented
@simularis Sure, please do. I think that would make the review easier. Thank you for the suggestion.

2024-02-24 01:45 UTC, lyt5410 reviewed
Hi @behzadsalimian @simularis, I reviewed the commits in this pull request and have the following comments.

Since this is our first measure package review under the new E+/Modelkit System, we are still trying to iron out some of the rules/processes as we work through this together. We made some updates to the Readme and User Guide as we reviewed this submission.

1. Please refer to the TechID naming guidance. When naming runs in case files, and make sure each case name is consistent with TechIDs used. See the updated User Guide on CEDARS (https://cedars.sound-data.com/deer-resources/tools/energy-plus/) and also a TechID Builder that we uploaded to the same CEDARS page to help with this process.

- Going forward the TechID fields should be the same as CommonTechID fields (Columns D,E,F and Columns G,H,I in the measure list spreadsheet). The CommonTechID columns were created to deal with some inconsistencies in TechID naming versus actual Tech cases used in the simulation, early in our development process. As new measures come out and we will eventually phase out the CommonTechID fields. The TechID naming guidance / TechID builder should be able to help to make each run unique such that the CommonTechID columns are no longer needed. This is to allow for minimal confusion for all stakeholders.

2. Rename "Measure_list.csv" to be more specific (i.e. SWXXX-MeasureName_Measure_list.csv), the part before "_Measure_list.csv" should be same as the measure folder name. This should allow for better traceability during post-processing.

cc: @JenMcW @amine-lazrak

2024-02-24 01:45 UTC, lyt5410 commented on scripts/data transformation/DMo.py
Did a test run with SWHC001-05 Wall Furnace_DMo, had to modify a few file path input lines but it works. The renaming fix here is proper.

2024-02-24 01:45 UTC, lyt5410 commented on residential measures/SWHC001-05 Wall Furnace/SWHC001-05 Wall Furnace_DMo/query_Wall Furnace.txt
Noted, this have not been tested yet this since for this branch this modified query_Wall Furnace.txt are not called in the rakefile.rb (currently it is still using the default query.txt)

2024-02-24 01:45 UTC, lyt5410 commented on scripts/data transformation/insert_normunits.py
This script is dependent on having "results-sizing-agg-SFm.csv', which was produced (guessing) by "result.py" (another commit), which I tested and got an error.

2024-02-24 01:45 UTC, lyt5410 commented on scripts/data transformation/insert_normunits.py
@behzadsalimian @simularis Please provide more instructions on the workflow of running this script. I've been doing some test runs and I am unable to run step 5 of this script (gives an ParserError on csv reading step). 
My understanding is that you would run the "result.py" to generate "results-sim-sizing.csv" and "results-sizing-agg.csv" and these results will be used in "insert_normunits.py" in conjunction with the "sfm_annual.csv" or "sim_annual.csv" from the default post-processing. Is this correct?

2024-02-24 01:54 UTC, amine-lazrak requested changes
Please find below a few general comments regarding the result.py file.

2024-02-24 01:54 UTC, amine-lazrak commented on residential measures/SWHC001-05 Wall Furnace/SWHC001-05 Wall Furnace_DMo/result.py
> +* Requires python >= 3.2 and additional package "tqdm"
Please update software requirements. The parameter `dtype` in `pandas.read_sql_query` was introduced in pandas [version 1.3.0](https://pandas.pydata.org/docs/reference/api/pandas.read_sql_query.html#:~:text=New%20in%20version%201.3.0.). which seems to require python >= 3.7.1

2024-02-24 01:54 UTC, amine-lazrak commented on residential measures/SWHC001-05 Wall Furnace/SWHC001-05 Wall Furnace_DMo/result.py
> +    $terminal1> python results.py results
I think this should be `$terminal1> python result.py "absolute\path\to\measure\folder\containing\cohorts\and\climates\csv\files"`. `python result.py results` didn't run.

2024-02-24 01:54 UTC, amine-lazrak commented on residential measures/SWHC001-05 Wall Furnace/SWHC001-05 Wall Furnace_DMo/result.py
> +"""
`modelkit rake results` will trigger other tasks only if any of the precursor files (root.pxt, etc.) have changed since the last run. Ideally, it would be good to incorporate this feature into Modelkit. In the meantime, I find this script pretty useful.

2024-02-24 01:54 UTC, amine-lazrak commented on residential measures/SWHC001-05 Wall Furnace/SWHC001-05 Wall Furnace_DMo/result.py
> +
Optional: It would be nice if you could add some error handling messages when the user provides inaccurate inputs (e.g. runs/ directory doesn't exist, etc.).

2024-03-20 18:12 UTC, simularis commented on residential measures/SWHC001-05 Wall Furnace/SWHC001-05 Wall Furnace_DMo/result.py
> +    $terminal1> python results.py results
Yes, this usage message was incorrect. See new pull request with better documentation.

2024-03-20 18:15 UTC, simularis commented on residential measures/SWHC001-05 Wall Furnace/SWHC001-05 Wall Furnace_DMo/result.py
> +"""
I think the limitation is in the rakefile only, which could be fixed. As another workaround, there might be a way to invoke the Modelkit results gathering function with a lightweight ruby script that wouldn't requiring major changes to the rakefile.

2024-03-20 18:16 UTC, simularis commented on residential measures/SWHC001-05 Wall Furnace/SWHC001-05 Wall Furnace_DMo/result.py
> +
Good point. As written, the python script will just skip any simulations that are missing. So you won't notice that in the output file.

2024-03-20 18:20 UTC, simularis commented on residential measures/SWHC001-05 Wall Furnace/SWHC001-05 Wall Furnace_DMo/query_Wall Furnace.txt
We did not want to break the data transformation script, so we ended up generating two results files. The default query is retained to generate results-summary.csv and feed into data transformation. The additional query file is used to generate a second set of results files, like results-sizing-agg-SFm.csv, and a further step to insert the sizing result into sim_annual.csv, but we need to document those additional steps better.

2024-03-20 18:22 UTC, simularis commented on residential measures/SWHC001-05 Wall Furnace/SWHC001-05 Wall Furnace_DMo/result.py
> +* Requires python >= 3.2 and additional package "tqdm"
Thank you for catching that. I created yet another pull request to just deal with this result script. Planning to merge the final edits for use into this measure.

2024-03-20 22:23 UTC, simularis commented on scripts/data transformation/DMo.py
Okay.

2024-03-20 22:25 UTC, simularis commented on scripts/data transformation/insert_normunits.py
Yes, this is correct. If you test it again and get an error, please share the error message. I could provide CSV files to test with but the TechIDs just changed, so I need to re-run models.

2024-03-21 15:04 UTC, simularis commented
To demonstrate the `results.py` and `insert_normunits.py` scripts, attached are the results for the DMo building type. 

I would like to code the steps to generate these into the rakefile or other supplemental script. In the meanwhile, here is what I entered on command line, including the revised results.py script in new location.

```
cd C:\DEER-Prototypes-EnergyPlus
cd "residential measures/SWHC001-05 Wall Furnace/SWHC001-05 Wall Furnace_DMo"
modelkit rake
python "../../../scripts/data transformation/DMo.py"
cp "../../../scripts/data transformation/sim_annual.csv" .
```

At this point, I have sim_annual.csv.

```
python "../../../scripts/result.py" . --queryfile "query_Wall Furnace.txt"
python "../../../scripts/data transformation/insert_normunits.py" results-sizing-agg.csv sim_annual.csv results-per-dwelling.csv sim_annual_withunits.csv "Coil:Heating:Fuel Design Size Nominal Capacity (W)" "CapOut-kBtuh" 0.2930710701832112 "Wall Furnace"
```

At this point, I have sim_annual_withunits.csv.

[SWHC001-05 Wall Furnace_DMo results.zip](https://github.com/sound-data/DEER-Prototypes-EnergyPlus/files/14696904/SWHC001-05.Wall.Furnace_DMo.results.zip)

2024-04-04 00:07 UTC, simularis commented
Just checking in. I believe we have addressed the review comments aside from the one about error handling messages in the result scraping script.

2024-04-04 20:25 UTC, amine-lazrak requested changes

2024-04-04 20:25 UTC, amine-lazrak commented on querylibrary/readme.md
> +python "../../scripts/result.py" "commercial measures/SWXX000-00 Measure Name/" --queryfile "querylibrary/query_benchmark.txt" --detailfile "commercial measures/SWXX000-00 Measure Name/results-sizing
I think the path should be "scripts/result.py" instead of "../../scripts/result.py" because the folders scripts and querylibrary are at the same level when at C:/DEER-Prototypes-EnergyPlus/

2024-04-04 22:57 UTC, lyt5410 commented
> To demonstrate the `results.py` and `insert_normunits.py` scripts, attached are the results for the DMo building type.
> 
> I would like to code the steps to generate these into the rakefile or other supplemental script. In the meanwhile, here is what I entered on command line, including the revised results.py script in new location.
> 
> ```
> cd C:\DEER-Prototypes-EnergyPlus
> cd "residential measures/SWHC001-05 Wall Furnace/SWHC001-05 Wall Furnace_DMo"
> modelkit rake
> python "../../../scripts/data transformation/DMo.py"
> cp "../../../scripts/data transformation/sim_annual.csv" .
> ```
> 
> At this point, I have sim_annual.csv.
> 
> ```
> python "../../../scripts/result.py" . --queryfile "query_Wall Furnace.txt"
> python "../../../scripts/data transformation/insert_normunits.py" results-sizing-agg.csv sim_annual.csv results-per-dwelling.csv sim_annual_withunits.csv "Coil:Heating:Fuel Design Size Nominal Capacity (W)" "CapOut-kBtuh" 0.2930710701832112 "Wall Furnace"
> ```
> 
> At this point, I have sim_annual_withunits.csv.
> 
> [SWHC001-05 Wall Furnace_DMo results.zip](https://github.com/sound-data/DEER-Prototypes-EnergyPlus/files/14696904/SWHC001-05.Wall.Furnace_DMo.results.zip)

Thanks for showing this. I did some test runs on my end. The scripts ran fine without error.
However, my numunits field is blank. So dues the "myunits_weighted.csv" and "results-per-dwelling.csv" tables generated.
Does this have to do with modelkit output settings (certain output fields not displayed in the output csvs from the idfs?)

Please advise @simularis.

See screenshot. I attached my output files as a zip here.

![image](https://github.com/sound-data/DEER-Prototypes-EnergyPlus/assets/16907311/e37f74d3-deab-4e72-a5e2-d47f6c9f6c2f)

[test_run_YL.zip](https://github.com/sound-data/DEER-Prototypes-EnergyPlus/files/14877895/test_run_YL.zip)
also current_msr_mat.csv didn't get updated with the correct norm unit (may cause some conflicts later?)

2024-04-09 15:32 UTC, simularis commented on querylibrary/readme.md
> +python "../../scripts/result.py" "commercial measures/SWXX000-00 Measure Name/" --queryfile "querylibrary/query_benchmark.txt" --detailfile "commercial measures/SWXX000-00 Measure Name/results-sizing
Yes, you are correct. Updated.

2024-04-09 15:35 UTC, simularis commented
@lyt5410 , thank you for testing and thorough debugging.

I think the issue is that the script was looking for the measure to be entered in the default Measure List file location, but I did not give instructions to take that step. I have updated the readme and script to try to make this more explicit.

2024-04-10 01:24 UTC, lyt5410 commented
@simularis, I reran results.py and insert_normunits.py for testing, script runs no problem now with correct outputs, after I added the records from "SWHC001-Wall-Furnace_Measure_list.xlsx" to the main measure list "DEER_EnergyPlus_Modelkit_Measure_list_working.xlsx" under data transformations folder. (the one with the suffix "_working" is the most up-to-date one. We will archive/remove the older one in a separate commit to avoid confusion, sorry about having 2 measure list files.)

@amine-lazrak This can be merged now. I tested the normunit extraction scripts and they are good.

2024-04-10 17:43 UTC, merged