System type development for cDXGF, cDXNH, cDXHP, cPVVG, cWVVG systems and related changes
sound-data/DEER-Prototypes-EnergyPlus pull request #29
Opened 2024-02-20 04:02 UTC by Justin-DeBlois

- [x] Provide a concise description of the measure, bug, or feature. Submit one PR per measure.
### A.  Changes needed to enable new system types
1.  Templates files in SWXX000-00 TRC System Types\X\cases\ with parameters assignments for cDXGF, cDXNH, cDXHP, cPVVG, cWVVG
	-cDXGF: Single zone packaged with gas furnace
	-cDXNH: Single zone packaged with no heat (appears to be new to eTRM)
	-cDXHP: Single zone packaged with HP
	-cPVVG: Single zone packaged variable volume with gas furnace
	-cWVVG: Multi-zone VAV with hot water coil, natural gas boilers, chilled water coil, water-cooled chillers
	-Parameters added in cases files to over-ride prototype defaults. The :main_oa_econ_max_temp parameter was added to the cohorts.csv file so that fixed DB temp economizer control could be used.

2.  The codes files were modified to add Title 24 drybulb limit temperatures for each climate zone.

3.  Enable ability to change prototypes with SZ default systems to MZ systems using hvac_confix and main_hvac_type. The way all_zones was defined for the prototypes, changing main_hvac_type did not combine zones into one system and changing hvac_config resulted in conflicts.
	-Affects root.pxt files
	-Some hvac_config options would result in two hvac systems being assigned to zones if a system name is assigned both in all_zones and irregular_zones, and other similar conflicts.

4.  Added "unitary_no_load_flow_method" parameter to parameterize the sizing method of the no load (minimum) flow for UnitarySystems with DX cooling.
	-Affects root.pxt (group "main_hvac_system"), hvac-zone.pxt and unitary.pxt files
	-Default is "SupplyAirFlowRate" which is the method previously hard-coded into unitary.pxt.
	-Changing to "FractionOfAutosizedCoolingValue" allows the minimum flow fraction to be defined, which was not working for systems with DX cooling when only using the sizing objects.

5.  Added capability to model systems with no heat, for cDXNH system type.
	-Affects hvac-zone.pxt file
	-Only activated if atu_reheat_coil_type, heat_coil_type & sub_heat_type = "NONE" or nil

6.  For cPVVG system type (packaged single zone variable volume gas furnace), UnitarySystem control_type = "SingleZoneVAV" works best. Added conditional logic to change to this method for single zone systems with fan_speed = "VARIABLE".
	-Affects unitary.pxt file
	-Activated for SZ systems with fan_speed = "VARIABLE".

### B.  Changes to min flow rate sizing
To determine minimum flow fraction based on the greater of ventilation requirement and minimum ratio. Currently for many configurations, ventilation rate is not being accounted for.

1.  Added "cool_flow_min_frac" parameter. "cool_flow_min_frac" is the minimum flow ratio in cooling in the sizing:zone object, and in some cases is the no load flow fraction in the AirLoopHVAC:UnitarySystem object
	-Affects root.pxt (group "main_hvac_zone"), hvac-zone.pxt and unitary.pxt files
	-Differs from ATU_flow_min_frac because ATU_flow_min_frac is used at the AirTerminal object and if is not autosized, ATU_flow_min_frac overrides the ventilation requirement.
	-If ATU_flow_min_frac is Autosize and cool_flow_min_frac is defined, then the VAV minimum flow fraction will be the greater of the ventilation rate and cool_flow_min_frac.
	-cool_flow_min_frac has default "nil" and this change is not activated unless the parameter is defined by input.

2.  Added parameter "design_spec_OA_name" to pass Design Specification OA object to ATU in order to size VAV minimum flowrate.
	-Affects hvac-zone.pxt, atu.pxt files
	-Activated by default

3.  Added EMS logic to resolve the following EnergyPlus limitation: UnitarySystemSizing of the no load airflow does not account for ventilation rate when there is a DX coil, so in some cases the no load flow is less than the design ventilation rate. An EMS program is added to fix this for units configured with DX cooling, CONSTANT compressor speed and VARIABLE fan_speed. This may remain an issue for any Unitary systems with multispeed compressors, two-speed fans or other configurations.
	-Affects unitary.pxt file
	-Activated if cool_coil_type == "DX-AIR" && dx_comp_speed == "CONSTANT" && fan_speed == "VARIABLE"
	-EMS program runs after UnitarySizing. It reads the ventilation requirement and the min load flow rate. If the min load flow rate is less than the ventilation requirement, it assigns the ventilation requirement as the new min load flow rate.

### C.  UnitarySystem HW coil autosizing error
1.  Added EMS workaround for bug identified in issue #26 re Unitary HW coil autosizing.
	-Affects unitary.pxt file
	-Activated for unitary systems with HW heating coil
	-EMS tests to see if coil has negligible capacity after UnitarySizing and turns it off if it does, preventing the coil from calling for HW flow.
	-Routine has to run each timestep to override coil control, but test indicated only 1% increase in run time

- [x] For a new measure, attach a workbook named DEER_EnergyPlus_Modelkit_Measure_list_working.xlsx, containing only rows used for post-processing the measure.
No new measure

- [x] Add comments in the code when necessary to facilitate the review process.

- [x] Add a comment before the added code, including the author's full name, company, and specifying if it's a bug fix, new measure, or feature.

- [x] For a new feature or bug, demonstrate the impact on energy consumption for selected cases with justification using plots and descriptions.

### Change to default energy consumption:

A.  New system types: Results showing the energy consumption for each new system and default system in the 2023 vintage, across CZ01, CZ12 and CZ15 and all prototypes.  [system-types-results-summary.csv](https://github.com/sound-data/DEER-Prototypes-EnergyPlus/files/14339154/system-types-results-summary.csv)

B.  Minimum Flow/Ventilation: For the default system types the minimum flow rate is now set to be at least as high as the ventilation requirement. Testing the 2020 vintage in CZ01, CZ12 and CZ15: for some buildings (EPr, ERC, OfS etc) there is <1% change. For others with higher ventilation requirements, the low turndown was resulting in the building being underventilated and this change is significant. Asm shows a 70% increase in energy consumption. Four buildings show a >10% increase in energy consumption: Asm, MBT, MLI, RSD. [Template_Changes_default_results-summary.xlsx](https://github.com/sound-data/DEER-Prototypes-EnergyPlus/files/14339158/Template_Changes_default_results-summary.xlsx)

C.  Coil UA fix: no impact to most cases. For cases that have the UA error on the system-level coil, there will be a small impact on energy. Tested one case (1996 Nrs CZ03) change in energy consumption <0.1%.  [UA_fix_pre-post_results.zip](https://github.com/sound-data/DEER-Prototypes-EnergyPlus/files/14339143/UA_fix_pre-post_results.zip)

	- [x] For a new measure, add a summary table showing total energy consumption per simulated case.

2024-02-25 19:24 UTC, amine-lazrak requested changes
Thank you for the provided template and prototype improvements. Below are a few comments on the suggested changes.

Regarding the cases with the system type cDXNH, I'm seeking clarification on whether they are intended to have no heating at all or this only applies specifically to the primary heating coils. Additionally, I couldn't locate the definition of this system type on the [eTRM table](https://www.caetrm.com/cpuc/table/buildinghvac/). Could you please direct me to where it's defined?

Furthermore, since you updated cWVVG to cAVVG, please ensure that this change is reflected in section A of your Pull Request description as well.

2024-02-25 19:24 UTC, amine-lazrak commented on templates/energyplus/templates/system/unitary.pxt
> +  control_type = "SingleZoneVAV"
The SingleZoneVAV control type is intended to only work with [specific coils](https://bigladdersoftware.com/epx/docs/22-2/input-output-reference/group-unitary-equipment.html#airloophvacunitarysystem:~:text=The%20cooling%20coil,based%20control%20method.). EnergyPlus will throw a warning similar to below if a different coil type is used:
```
** Warning ** AirLoopHVAC:UnitarySystem: HALL EL1 CORE SPC (G.C5) SZ-VAV UNITARY
   **   ~~~   ** ASHRAE90.1 control method requires specific cooling coil types.
   **   ~~~   ** Valid cooling coil types are Coil:Cooling:Water, Coil:Cooling:Water:DetailedGeometry and Coil:Cooling:DX:SingleSpeed.
   **   ~~~   ** The input cooling coil type = COIL:COOLING:DX:MULTISPEED. This coil will not be modeled using the ASHRAE 90.1 algorithm.
```
Maybe add a condition to make sure the user is not unintentionally using the wrong control type. It seems like as long as the `dx_comp_speed == CONSTANT` or `cool/heat_coil_type == WATER` the coil will be compatible.

2024-02-25 19:24 UTC, amine-lazrak commented on templates/energyplus/templates/system/unitary.pxt
The EMS workaround for the bug identified in issue #26 does not appear to resolve the UA sizing issue. This problem persists, notably in known cases such as NRs-CZ03-1996. As you noted, the issue revolves around the low loads experienced by the unitary system coil during the design day. The problem arises when the return air, which is warm and has a high flow rate, mixes with OA, which is cold and has a smaller flow rate. This mixing results in a coil inlet temperature that is sufficiently high, rendering the coil unnecessary since the SAT setpoint falls within the 12-15°C range. Perhaps we should consider ensuring, but only during the design day, that either the outside air flow rate is high enough to lower the mixed air temperature to a few degrees below 12°C or increasing the SAT setpoint.

2024-02-25 19:24 UTC, amine-lazrak commented on templates/energyplus/templates/system/unitary.pxt
> +%>
Although simulations ran successfully, there appear to be several severe errors, as exemplified below, that require attention in cPVVG cases. While I haven't tested all prototypes, these errors are evident in Asm-CZ03-2023 and OfL-CZ03-2023. It is likely that these errors stem from the EMS minimum flow overriding sequence.
```
   ** Severe  ** AirLoopHVAC:UnitarySystem = NE CORNER OFFICE SZ-VAV UNITARY
   **   ~~~   **  For SingleZoneVAV control the No Load Supply Air Flow Rate must be less than both the cooling and heating supply air flow rates.
   **   ~~~   **  The SingleZoneVAV control No Load Supply Air Flow Rate is reset to 0.34512 and the simulation continues.
   ** Warning ** The Standard Ratings is calculated for Coil:Cooling:DX:SingleSpeed = NE CORNER OFFICE SZ-VAV COOLING COIL but not at the AHRI test condition due to curve out of bound.
   **   ~~~   **  Review the Standard Ratings calculations in the Engineering Reference for this coil type. Also, use Output:Diagnostics, DisplayExtraWarnings for further guidance.
   **   ~~~   ** CheckCurveLimitsForStandardRatings: The max and/or min limits specified in the corresponding curve objects
   **   ~~~   **  do not include the AHRI test conditions required to calculate one or more of the Standard Rating values.
   **   ~~~   ** Coil:Cooling:DX:SingleSpeed=NE CORNER OFFICE SZ-VAV COOLING COIL:  Integrated Energy Efficiency Ratio (IEER) calculated is not at the AHRI test condition.
   **   ~~~   **  Check limits in Total Cooling Capacity Function of Temperature Curve, Curve Type = Curve:Biquadratic, Curve Name = NE CORNER OFFICE SZ-VAV COOL-CAP-FT
   **   ~~~   **  Check limits in EIR Function of Temperature Curve, Curve Type = Curve:Biquadratic, Curve Name = NE CORNER OFFICE SZ-VAV COOL-EIR-FT
   ************* SizeUnitarySystem: Potential issue with equipment sizing for AirLoopHVAC:UnitarySystem NW CORNER OFFICE SZ-VAV UNITARY
   **   ~~~   ** User-Specified Minimum Supply Air Temperature [C] = 2.00000
   **   ~~~   ** differs from Design Size Minimum Supply Air Temperature [C] = 15.60130
   **   ~~~   ** This may, or may not, indicate mismatched component sizes.
   **   ~~~   ** Verify that the value entered is intended and is consistent with other components.
   ** Severe  ** AirLoopHVAC:UnitarySystem = NW CORNER OFFICE SZ-VAV UNITARY
   **   ~~~   **  For SingleZoneVAV control the No Load Supply Air Flow Rate must be less than both the cooling and heating supply air flow rates.
   **   ~~~   **  The SingleZoneVAV control No Load Supply Air Flow Rate is reset to 0.38589 and the simulation continues.
   ** Warning ** The Standard Ratings is calculated for Coil:Cooling:DX:SingleSpeed = NW CORNER OFFICE SZ-VAV COOLING COIL but not at the AHRI test condition due to curve out of bound.
   **   ~~~   **  Review the Standard Ratings calculations in the Engineering Reference for this coil type. Also, use Output:Diagnostics, DisplayExtraWarnings for further guidance.
   **   ~~~   ** CheckCurveLimitsForStandardRatings: The max and/or min limits specified in the corresponding curve objects
   **   ~~~   **  do not include the AHRI test conditions required to calculate one or more of the Standard Rating values.
   **   ~~~   ** Coil:Cooling:DX:SingleSpeed=NW CORNER OFFICE SZ-VAV COOLING COIL:  Integrated Energy Efficiency Ratio (IEER) calculated is not at the AHRI test condition.
   **   ~~~   **  Check limits in Total Cooling Capacity Function of Temperature Curve, Curve Type = Curve:Biquadratic, Curve Name = NW CORNER OFFICE SZ-VAV COOL-CAP-FT
   **   ~~~   **  Check limits in EIR Function of Temperature Curve, Curve Type = Curve:Biquadratic, Curve Name = NW CORNER OFFICE SZ-VAV COOL-EIR-FT
   ************* SizeUnitarySystem: Potential issue with equipment sizing for AirLoopHVAC:UnitarySystem SE CORNER OFFICE SZ-VAV UNITARY
   **   ~~~   ** User-Specified Minimum Supply Air Temperature [C] = 2.00000
   **   ~~~   ** differs from Design Size Minimum Supply Air Temperature [C] = 15.60147
   **   ~~~   ** This may, or may not, indicate mismatched component sizes.
   **   ~~~   ** Verify that the value entered is intended and is consistent with other components.
   ** Severe  ** AirLoopHVAC:UnitarySystem = SE CORNER OFFICE SZ-VAV UNITARY
   **   ~~~   **  For SingleZoneVAV control the No Load Supply Air Flow Rate must be less than both the cooling and heating supply air flow rates.
   **   ~~~   **  The SingleZoneVAV control No Load Supply Air Flow Rate is reset to 0.37116 and the simulation continues.
```

2024-02-26 15:22 UTC, Justin-DeBlois commented
> Thank you for the provided template and prototype improvements. Below are a few comments on the suggested changes.
> 
> Regarding the cases with the system type cDXNH, I'm seeking clarification on whether they are intended to have no heating at all or this only applies specifically to the primary heating coils. Additionally, I couldn't locate the definition of this system type on the [eTRM table](https://www.caetrm.com/cpuc/table/buildinghvac/). Could you please direct me to where it's defined?
> 
> Furthermore, since you updated cWVVG to cAVVG, please ensure that this change is reflected in section A of your Pull Request description as well.

Thanks for your review, I updated the pull request description.

The cDXNH system is not included in the eTRM. Lake Casco emailed a request to DEER Support to have it added, with more information. It is for systems with no heating at all.

2024-02-26 15:29 UTC, Justin-DeBlois commented on templates/energyplus/templates/system/unitary.pxt
> The EMS workaround for the bug identified in issue #26 does not appear to resolve the UA sizing issue. This problem persists, notably in known cases such as NRs-CZ03-1996. As you noted, the issue revolves around the low loads experienced by the unitary system coil during the design day. The problem arises when the return air, which is warm and has a high flow rate, mixes with OA, which is cold and has a smaller flow rate. This mixing results in a coil inlet temperature that is sufficiently high, rendering the coil unnecessary since the SAT setpoint falls within the 12-15°C range. Perhaps we should consider ensuring, but only during the design day, that either the outside air flow rate is high enough to lower the mixed air temperature to a few degrees below 12°C or increasing the SAT setpoint.

I agree, this is another workaround. The benefit would be that if someone needs to change the HW pump type to constant volume or riding the pump curve, the simulations will no longer fail. My opinion is it's a reasonable workaround because systems with very low ventilation load in many cases would be designed without a system heating coil. I'm hesitant to change the sizing method to increase ventilation heating load in a way that would affect all prototypes because it might affect boiler capacity or other sizing in systems that weren't experiencing the error. However I can remove this script and leave this issue to be resolved separately if you prefer.

2024-02-26 18:29 UTC, Justin-DeBlois commented on templates/energyplus/templates/system/unitary.pxt
> +%>
> Although simulations ran successfully, there appear to be several severe errors, as exemplified below, that require attention in cPVVG cases. While I haven't tested all prototypes, these errors are evident in Asm-CZ03-2023 and OfL-CZ03-2023. It is likely that these errors stem from the EMS minimum flow overriding sequence.
> 
> ```
>    ** Severe  ** AirLoopHVAC:UnitarySystem = NE CORNER OFFICE SZ-VAV UNITARY
>    **   ~~~   **  For SingleZoneVAV control the No Load Supply Air Flow Rate must be less than both the cooling and heating supply air flow rates.
>    **   ~~~   **  The SingleZoneVAV control No Load Supply Air Flow Rate is reset to 0.34512 and the simulation continues.
>    ** Warning ** The Standard Ratings is calculated for Coil:Cooling:DX:SingleSpeed = NE CORNER OFFICE SZ-VAV COOLING COIL but not at the AHRI test condition due to curve out of bound.
>    **   ~~~   **  Review the Standard Ratings calculations in the Engineering Reference for this coil type. Also, use Output:Diagnostics, DisplayExtraWarnings for further guidance.
>    **   ~~~   ** CheckCurveLimitsForStandardRatings: The max and/or min limits specified in the corresponding curve objects
>    **   ~~~   **  do not include the AHRI test conditions required to calculate one or more of the Standard Rating values.
>    **   ~~~   ** Coil:Cooling:DX:SingleSpeed=NE CORNER OFFICE SZ-VAV COOLING COIL:  Integrated Energy Efficiency Ratio (IEER) calculated is not at the AHRI test condition.
>    **   ~~~   **  Check limits in Total Cooling Capacity Function of Temperature Curve, Curve Type = Curve:Biquadratic, Curve Name = NE CORNER OFFICE SZ-VAV COOL-CAP-FT
>    **   ~~~   **  Check limits in EIR Function of Temperature Curve, Curve Type = Curve:Biquadratic, Curve Name = NE CORNER OFFICE SZ-VAV COOL-EIR-FT
>    ************* SizeUnitarySystem: Potential issue with equipment sizing for AirLoopHVAC:UnitarySystem NW CORNER OFFICE SZ-VAV UNITARY
>    **   ~~~   ** User-Specified Minimum Supply Air Temperature [C] = 2.00000
>    **   ~~~   ** differs from Design Size Minimum Supply Air Temperature [C] = 15.60130
>    **   ~~~   ** This may, or may not, indicate mismatched component sizes.
>    **   ~~~   ** Verify that the value entered is intended and is consistent with other components.
>    ** Severe  ** AirLoopHVAC:UnitarySystem = NW CORNER OFFICE SZ-VAV UNITARY
>    **   ~~~   **  For SingleZoneVAV control the No Load Supply Air Flow Rate must be less than both the cooling and heating supply air flow rates.
>    **   ~~~   **  The SingleZoneVAV control No Load Supply Air Flow Rate is reset to 0.38589 and the simulation continues.
>    ** Warning ** The Standard Ratings is calculated for Coil:Cooling:DX:SingleSpeed = NW CORNER OFFICE SZ-VAV COOLING COIL but not at the AHRI test condition due to curve out of bound.
>    **   ~~~   **  Review the Standard Ratings calculations in the Engineering Reference for this coil type. Also, use Output:Diagnostics, DisplayExtraWarnings for further guidance.
>    **   ~~~   ** CheckCurveLimitsForStandardRatings: The max and/or min limits specified in the corresponding curve objects
>    **   ~~~   **  do not include the AHRI test conditions required to calculate one or more of the Standard Rating values.
>    **   ~~~   ** Coil:Cooling:DX:SingleSpeed=NW CORNER OFFICE SZ-VAV COOLING COIL:  Integrated Energy Efficiency Ratio (IEER) calculated is not at the AHRI test condition.
>    **   ~~~   **  Check limits in Total Cooling Capacity Function of Temperature Curve, Curve Type = Curve:Biquadratic, Curve Name = NW CORNER OFFICE SZ-VAV COOL-CAP-FT
>    **   ~~~   **  Check limits in EIR Function of Temperature Curve, Curve Type = Curve:Biquadratic, Curve Name = NW CORNER OFFICE SZ-VAV COOL-EIR-FT
>    ************* SizeUnitarySystem: Potential issue with equipment sizing for AirLoopHVAC:UnitarySystem SE CORNER OFFICE SZ-VAV UNITARY
>    **   ~~~   ** User-Specified Minimum Supply Air Temperature [C] = 2.00000
>    **   ~~~   ** differs from Design Size Minimum Supply Air Temperature [C] = 15.60147
>    **   ~~~   ** This may, or may not, indicate mismatched component sizes.
>    **   ~~~   ** Verify that the value entered is intended and is consistent with other components.
>    ** Severe  ** AirLoopHVAC:UnitarySystem = SE CORNER OFFICE SZ-VAV UNITARY
>    **   ~~~   **  For SingleZoneVAV control the No Load Supply Air Flow Rate must be less than both the cooling and heating supply air flow rates.
>    **   ~~~   **  The SingleZoneVAV control No Load Supply Air Flow Rate is reset to 0.37116 and the simulation continues.
> ```

This seems to be happening in systems where the ventilation load is low and the EMS IF statements are false. I tried removing the EMS program and got the same errors. It seems like heating flow rate is calculated separately and when it is autosized below the default no load airflow (67% of the cooling design airflow), this error is thrown and the no load airflow is decreased.

I changed the EMS program to increase the heating airflow rate if it's less than the ventilation rate, but that's a separate situation from the error above (lines A12-A14).

I'm not sure how to resolve this error in the UnitarySystem object since I don't see any option to tie heating air flow autosizing to cooling or no load airflow autosizing, so I wrote it into the EMS program (lines A8-A11).

2024-02-26 18:29 UTC, Justin-DeBlois commented on templates/energyplus/templates/system/unitary.pxt
> +  control_type = "SingleZoneVAV"
Good point, I added the conditionals

2024-02-26 18:31 UTC, Justin-DeBlois commented
@amine-lazrak I responded to your comments and updated the pull request.

2024-02-26 20:55 UTC, amine-lazrak commented on templates/energyplus/templates/system/unitary.pxt
Yes, let's leave it to be resolved separately and merge it with `main` once finalized.

2024-02-27 14:12 UTC, Justin-DeBlois commented on templates/energyplus/templates/system/unitary.pxt
I removed the script from unitary.pxt

2024-02-27 16:05 UTC, amine-lazrak commented
@Justin-DeBlois one last thing: Since cDXNH models cases with no heating at all, the templates need to be updated to remove reheat coils as well. The way these cases are set up now only removes the main heating coil, I can still see significant space heating energy consumption.

2024-02-27 16:40 UTC, Justin-DeBlois commented
> @Justin-DeBlois one last thing: Since cDXNH models cases with no heating at all, the templates need to be updated to remove reheat coils as well. The way these cases are set up now only removes the main heating coil, I can still see significant space heating energy consumption.

The remaining heating is from the ALT and irregular_zones systems, the cDXNH systems only serve the main_ group and don't have reheat coils.

2024-02-27 17:27 UTC, amine-lazrak commented
Thank you for the updates, merging the branch now.

2024-02-27 17:28 UTC, merged