Develop commercial HVAC boiler variants [feature]
sound-data/DEER-Prototypes-EnergyPlus pull request #37
Opened 2024-03-22 17:16 UTC by simularis

# Pull Request (PR) Description

This pull request includes template modifications to enable steam boilers and condensing boilers in commercial buildings as a prerequisite for modeling measure SWHC004 Space Heating Boiler.

For these boiler variants, we have made the following setup: 

* Adding a new parameter (fluid_type) to implement steam boiler options (hw.pxt)
* Implementing new objects and updating logic to trigger steam boiler type configurations (hw.pxt)
* Adding new parameter (max_loop_temp) to determine maximum loop temperature for the plant loop (hw.pxt), which varies between condensing and non-condensing boilers
* Adding new parameter (min_loop_temp) to determine minimum loop temperature for the plant loop (hw.pxt)
* Adding new label “STEAMBOILER” for the parameter (heating_source) to add class list “Boiler:Steam” (hw.pxt)
* Adding new label “VARIABLESPEEDCONDENSATE” for the parameter (pump_type) to add class list “Pump:VariableSpeed:Condensate” for the steam boiler (hw.pxt)
* Adding class list “Boiler: Steam” to add steam boiler (hw.pxt)
* Adding class list “Pipe: Adiabatic: Steam” and its corresponding branches (hw.pxt)
* Adding “Heating Coil Controller” for steam heat coil type (ahu.pxt) 
* Adding branches for (reheat_coil_type == “STEAM”) (atu.pxt)
* Adding label "STEAM" for parameter (reheat_coil_type) in class list “AirTerminal:SingleDuct:VAV:Reheat” (atu.pxt)

Measure setup will be submitted separately.

Behzad Rizi (@behzadsalimian) was the main contributor for this work, with code review by Nicholas Fette (Solaris Technical). 

### PR Author
- [x] Make sure the PR branch is up to date with main branch at the time of the PR submission
- [x] Craft a succinct title that effectively encapsulates the essence of the pull request, providing a general overview of the proposed changes.
- [x] Label the PR with at least one of the following: New Measure, Bug, or Feature.
- [x] Provide a concise description of the measure, bug, or feature. Submit one PR per measure.
- N/A - For a new measure, attach a workbook named DEER_EnergyPlus_Modelkit_Measure_list_working.xlsx, containing only rows used for post-processing the measure.
- [x] Add comments in the code when necessary to facilitate the review process.
- [x] Add a comment before the added code, including the author's full name, company, and specifying if it's a bug fix, new measure, or feature.
- [ ] For a new feature or bug, demonstrate the impact on energy consumption for selected cases with justification using plots and descriptions.
- N/A - For a new measure, add a summary table showing total energy consumption per simulated case.
### PR Reviewer
- [ ] Conduct a thorough code review.
- [ ] If the branch is behind the main, merge the branch locally to check for potential conflicts.
- [ ] If a bug, locally reproduce it and compare energy consumptions before and after.
- [ ] Explore creative ways to stress-test the code.
- [ ] Locally check the error file and other outputs.

2024-05-02 23:59 UTC, amine-lazrak requested changes
Thank you for including the steam boiler option. I noticed a few issues in specific cases. I'll proceed with merging once these issues have been addressed.

2024-05-02 23:59 UTC, amine-lazrak commented on prototypes/ECC/templates/root.pxt
> +  parameter "min_loop_temp", :default=>10  # (10 | 10 )
This line `parameter "min_loop_temp", :default=>10  # (10 | 10 )` seems to be repeated twice in each modified prototype.

2024-05-02 23:59 UTC, amine-lazrak commented on templates/energyplus/templates/zonehvac/atu.pxt
> +  <%= atu_name %> ATU Heating Coil,  !- Reheat Coil Name
I ran several simulations, but the ones for MBT failed. I believe this happened because `<%= atu_name %> ATU Heating Coil,  !- Reheat Coil Name` needs to be placed outside the if statement. Otherwise, the coil name won't be printed correctly.

2024-05-02 23:59 UTC, amine-lazrak commented on templates/energyplus/templates/zonehvac/atu.pxt
>    <%= atu_name %> Heating Coil Demand Outlet Node;  !- Component 1 Outlet Node Name
Nrs, OfL and Hsp fail when ran in CZ16 for the `Boiler_Steam` case. Some branches seem to use steam and water fluid types on the same `plantloop`. EnergyPlus outputs the following error `** Severe  ** BranchList=HW DEMAND BRANCHES has mixed fluid types in its nodes.`

2024-05-02 23:59 UTC, amine-lazrak commented on commercial measures/HVAC_Boiler_Variants/Ex/cases/ECC.csv
> +skip,case_name,:hw_heating_source,:hw_fluid_type,:hw_boiler_duplicate_1,:main_atu_reheat_coil_type,:hw_pump_type,:hw_boiler_eff,:hw_boiler_type,:hw_setpoint_type,:main_heat_coil_type,:kitch_heat_coil
I think the parameter `hw_boiler_duplicate_1` must be `hw_boiler_duplicate`. Otherwise, `hw_boiler_duplicate` will remain equal to default. Modelkit doesn't seem to output an error when an undefined parameter is specified in `cases` folder.

2024-07-18 16:52 UTC, amine-lazrak commented
@simularis Could you please take a look at the comments on the PR and make the necessary changes? Also, could you merge the main branch to ensure there are no conflicts? Thanks!

2026-04-04 00:26 UTC, nfette commented
This PR is a subset of the measure setup #91, where we addressed some of these comments during review of the SWHC004 commercial measure setup. Let me merge in recent template changes from that branch and see if that addresses the comments.

2026-04-04 00:39 UTC, nfette commented on templates/energyplus/templates/zonehvac/atu.pxt
> +  <%= atu_name %> ATU Heating Coil,  !- Reheat Coil Name
We added the Reheat Coil Name line in each branch of the IF statement.

2026-04-09 23:33 UTC, behzadsalimian commented on templates/energyplus/templates/zonehvac/atu.pxt
>    <%= atu_name %> Heating Coil Demand Outlet Node;  !- Component 1 Outlet Node Name
For these building types, OfL, Nrs, EUn, Hsp and MBT, since the default values for the alt_atu_reheat_coil_type, alt_heat_coil_type in the root file is WATER, to resolve this issue for the steam boiler cases, in the cases files, we assign STEAM to all the existing heating coil types.
<img width="640" height="150" alt="image" src="https://github.com/user-attachments/assets/ec98cd2e-7c32-4a2b-9b96-6defb4e465fc" />

<img width="686" height="471" alt="image" src="https://github.com/user-attachments/assets/9a5a0f30-ca4c-41ac-af26-57218aad5bfb" />

2026-04-09 23:40 UTC, behzadsalimian commented on templates/energyplus/templates/zonehvac/atu.pxt
> +  <%= atu_name %> ATU Heating Coil,  !- Reheat Coil Name
Yes, we added the reheat coil name to resolve the issue.
<img width="961" height="425" alt="image" src="https://github.com/user-attachments/assets/d0c643cd-7467-49ea-9cf3-88f07da7f2b1" />

2026-04-10 17:28 UTC, behzadsalimian commented on commercial measures/HVAC_Boiler_Variants/Ex/cases/ECC.csv
> +skip,case_name,:hw_heating_source,:hw_fluid_type,:hw_boiler_duplicate_1,:main_atu_reheat_coil_type,:hw_pump_type,:hw_boiler_eff,:hw_boiler_type,:hw_setpoint_type,:main_heat_coil_type,:kitch_heat_coil
That's correct. Parameter "hw_boiler_duplicate_1" no longer exists in the template and prototype. The default value for the "hw_boiler_duplicate" parameter is TRUE in the prototypes (root.pxt) for all commercial buildings. We corrected the parameter name in the cases files and set "hw_boiler_duplicate" to TRUE for all techIDs, steam, and HW boilers.

2026-04-10 18:06 UTC, behzadsalimian commented on prototypes/ECC/templates/root.pxt
> +  parameter "min_loop_temp", :default=>10  # (10 | 10 )
That's correct. There are two lines in the commercial prototypes (root.pxt) that have repeated twice: the parameter "min_loop_temp". I've removed the duplicate line in all prototypes.

2026-04-18 00:04 UTC, sepideh-QEA commented
Closing #37 to avoid duplication; the full HVAC boiler variant support + measure setup is maintained in #91. Please review/continue comments in #91.

2026-04-18 00:04 UTC, closed without merging