SWHC023-05 Enhanced Ventilation for Packaged HVAC
sound-data/DEER-Prototypes-EnergyPlus pull request #56
Opened 2024-05-03 22:48 UTC by Justin-DeBlois

# Enhanced Ventilation for Packaged HVAC

Energy Modeling: Yiyi Chu @Cyy-fresh1994
Postprocessing: Debrudra Mitra @Debrudra20

This measure adds a variable frequency drive (VFD) to an existing packaged single-zone direct expansion (DX) HVAC unit with an economizer. The VFD operates at three discrete speeds based on ventilation and cooling or heating load.

Measure list: [DEER_EnergyPlus_Modelkit_Measure_list_enhancedVentilation.xlsx](https://github.com/sound-data/DEER-Prototypes-EnergyPlus/files/15205509/DEER_EnergyPlus_Modelkit_Measure_list_enhancedVentilation.xlsx)

Energy Consumption: [meas_impacts_2024_com_enhVent.csv](https://github.com/sound-data/DEER-Prototypes-EnergyPlus/files/15205514/meas_impacts_2024_com_enhVent.csv)

### PR Author
- [x] Make sure the PR branch is up to date with main branch at the time of the PR submission
- [x] Craft a succinct title that effectively encapsulates the essence of the pull request, providing a general overview of the proposed changes.
- [x] Label the PR with at least one of the following: New Measure, Bug, or Feature.
- [x] Provide a concise description of the measure, bug, or feature. Submit one PR per measure.
- [x] For a new measure, attach a workbook named DEER_EnergyPlus_Modelkit_Measure_list_working.xlsx, containing only rows used for post-processing the measure.
- [x] Add comments in the code when necessary to facilitate the review process.
- [x] Add a comment before the added code, including the author's full name, company, and specifying if it's a bug fix, new measure, or feature.
- [x] For a new feature or bug, demonstrate the impact on energy consumption for selected cases with justification using plots and descriptions.
- [x] For a new measure, add a summary table showing total energy consumption per simulated case.
### PR Reviewer
- [ ] Conduct a thorough code review.
- [ ] If the branch is behind the main, merge the branch locally to check for potential conflicts.
- [ ] If a bug, locally reproduce it and compare energy consumptions before and after.
- [ ] Explore creative ways to stress-test the code.
- [ ] Locally check the error file and other outputs.

2024-06-28 15:40 UTC, amine-lazrak commented
@Justin-DeBlois We are just about to get to review this measure implementation. As you submitted this PR weeks ago, the main branch has seen some updates since then. Could you please merge the latest changes from the main branch into yours? This will help ensure that your PR is up-to-date and that any conflicts are resolved with your expertise.

Thank you!

2024-06-28 18:24 UTC, Justin-DeBlois commented
> @Justin-DeBlois We are just about to get to review this measure implementation. As you submitted this PR weeks ago, the main branch has seen some updates since then. Could you please merge the latest changes from the main branch into yours? This will help ensure that your PR is up-to-date and that any conflicts are resolved with your expertise.
> 
> Thank you!

@amine-lazrak The branch should be ready to review now

2024-07-18 23:03 UTC, lyt5410 commented
@amine-lazrak I reviewed this and test ran few cases. This is good to merge. I had to push an update (66f385cc3a745a991855a366e9ab047fd9cd63b2) of the post-processing to make the normalizing unit populate correctly.

2026-05-12 17:21 UTC, Justin-DeBlois commented
@sepideh-QEA This pull request wasn't merged but the measure was approved here: https://www.caetrm.com/measure/SWHC023/07/

2026-06-14 22:45 UTC, nfette requested changes
IMHO, this PR is ready to merge. One minor change suggested below.

2026-06-14 22:45 UTC, nfette commented on prototypes/Gro/templates/root.pxt.bak
Delete Notepad++ backup file.

2026-06-14 22:55 UTC, nfette commented
For completeness of the setup in the repository, you could also save a copy of your measure list workbook under the measure folder (commercial measures/SWHC023-05 EnhVent). However, you did follow the official procedure to attach the workbook here and in eTRM.

2026-06-16 14:56 UTC, Justin-DeBlois commented on prototypes/Gro/templates/root.pxt.bak
I removed this file.

2026-08-21 03:47 UTC, sepideh-QEA commented
This modeling submission was approved and published in eTRM as SWHC023-07. The repository folder can retain its original development name, SWHC023-05 EnhVent, to preserve the reviewed model setup and its internal references. We are requesting the eTRM GitHub link to be updated to the corresponding folder on main. 
https://github.com/sound-data/DEER-Prototypes-EnergyPlus/tree/main/commercial%20measures/SWHC023-05%20EnhVent

2026-08-21 03:49 UTC, merged