Disable EMS
sound-data/DEER-Prototypes-EnergyPlus pull request #60
Opened 2024-05-08 01:22 UTC by simularis

# Pull Request (PR) Description

#29 seems to break the linked sizing feature of modelkit in commercial prototypes. This pull request is meant to restore the ability to do linked-sizing.

- Creates a new parameter `disable_ems`
- Also addresses #59 

#### The problem

To reproduce the error when utilizing linked-sizing:

- User has a cases CSV file with the column `sizing_case` and at least one row refers to another.
- User composes linked-size models with command line `modelkit rake hardsize` or goes straight ahead to simulation with `modelkit rake`. The resulting models look like `instance-hardsize.idf`.
- After running the models, the user may see an error message in `instance-hardsize-out.err` that there is no System:Sizing object, although there are Autosize input fields present.

#### Proposed solution

The proposed solution is to disable the block of EMS logic in `unitary.pxt` added recently, by creating a parameter to guard that block of code. The logic will be enabled by default (`disable_ems` = false), but users can include `disable_ems` = true as an input parameter to turn it off.

### PR Author
- [X] Make sure the PR branch is up to date with main branch at the time of the PR submission
- [X] Craft a succinct title that effectively encapsulates the essence of the pull request, providing a general overview of the proposed changes.
- [ ] Label the PR with at least one of the following: New Measure, Bug, or Feature.
- [X] Provide a concise description of the measure, bug, or feature. Submit one PR per measure.
- [ ] For a new measure, attach a workbook named DEER_EnergyPlus_Modelkit_Measure_list_working.xlsx, containing only rows used for post-processing the measure.
- [x] Add comments in the code when necessary to facilitate the review process.
- [x] Add a comment before the added code, including the author's full name, company, and specifying if it's a bug fix, new measure, or feature.
- [ ] For a new feature or bug, demonstrate the impact on energy consumption for selected cases with justification using plots and descriptions.
- [ ] For a new measure, add a summary table showing total energy consumption per simulated case.
### PR Reviewer
- [ ] Conduct a thorough code review.
- [ ] If the branch is behind the main, merge the branch locally to check for potential conflicts.
- [ ] If a bug, locally reproduce it and compare energy consumptions before and after.
- [ ] Explore creative ways to stress-test the code.
- [ ] Locally check the error file and other outputs.

2024-05-08 01:23 UTC, simularis commented on templates/energyplus/templates/system/unitary.pxt
Here we create a new parameter, which will pass through to root prototypes.

2024-05-08 01:24 UTC, simularis commented on templates/energyplus/templates/system/unitary.pxt
> +%>
Here we guard the EMS code with an IF-clause.

2024-05-08 01:25 UTC, simularis commented on templates/energyplus/templates/zonehvac/hvac-zone.pxt
> +
Unitary template is often called from hvac-zone, so need the parameter here, too.

2024-05-08 01:26 UTC, simularis commented on templates/energyplus/templates/zonehvac/hvac-zone.pxt
> +  :disable_ems
The unitary_parameters list will feed into the insert unitary statement later.

2024-05-08 01:26 UTC, simularis commented on prototypes/ECC/templates/root.pxt
>      parameter "oa_person", :default => 0['CFM']
No need to redefine it, get the default value from hvac-zone.

2024-05-08 01:28 UTC, simularis commented on prototypes/ECC/templates/root.pxt
Pass the building-level default parameters for hvac-zone into the template here. This also includes `oa_person` (default 0) and `sat_min_dt` (unused by template).

2024-05-08 01:28 UTC, simularis commented on prototypes/ECC/templates/root.pxt
> +    **(space_hvac.building | zone_hvac_group)
Some prototypes have irregular_zones. Pass the building-level parameters for hvac-zone here, also.

2024-07-03 20:00 UTC, amine-lazrak requested changes
Thank you @simularis for adding the new parameter. Could you please merge the updated main branch with this one for an easier integration after review. I only had a minor comment that you will find below.

2024-07-03 20:00 UTC, amine-lazrak commented on templates/energyplus/templates/zonehvac/hvac-zone.pxt
> +
I think the new lines 394 and 395 should be placed outside the rule "hvac_type_ideal".

2024-07-16 21:58 UTC, simularis commented
@amine-lazrak, thank you for the review and catching the hvac_type_ideal rule. I made the requested changes.

2024-07-18 16:45 UTC, merged